version: '3'
services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=admin
      - DB_NAME=demodb
      - JWT_SECRET=secretito123
      - PORT=3000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=demodb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
